# Generated by Django 5.0 on 2023-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_remove_animal_entrada_remove_animal_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(default='small', max_length=200),
            preserve_default=False,
        ),
    ]
