# Generated by Django 5.0 on 2023-12-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_roles_alter_employee_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
