# Generated by Django 5.0 on 2023-12-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='saida',
        ),
    ]
