# Generated by Django 5.0 on 2023-12-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_alter_owner_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='zip',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
