# Generated by Django 5.0 on 2023-12-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0006_alter_employee_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='greed',
            new_name='breed',
        ),
        migrations.AlterField(
            model_name='owner',
            name='zip',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
