# Generated by Django 5.0 on 2023-12-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_remove_animal_entrada_remove_animal_saida'),
        ('housing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_appointment', models.DateField()),
                ('next_appointment', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('appointment_comments', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.animal')),
            ],
        ),
        migrations.CreateModel(
            name='HousingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cleaning', models.DateField()),
                ('next_cleaning', models.DateField()),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.housing')),
            ],
        ),
    ]
