# Generated by Django 5.0 on 2023-12-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_appointment', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('appointment_comments', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.animal')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(editable=False, max_length=200)),
                ('animal_greed', models.CharField(editable=False, max_length=200)),
                ('last_appointment', models.DateField()),
                ('next_appointment', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('appointment_comments', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.animal')),
            ],
        ),
        migrations.CreateModel(
            name='HousingManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_cleaning', models.DateField()),
                ('next_cleaning', models.DateField()),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registers.housing')),
            ],
        ),
    ]
