# Generated by Django 5.0 on 2023-12-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealth',
            name='animal_greed',
            field=models.CharField(default='Pinscher', editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='animal_type',
            field=models.CharField(default='Small', editable=False, max_length=200),
            preserve_default=False,
        ),
    ]
