# Generated by Django 5.0 on 2023-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalhealth',
            name='last_appointment',
            field=models.DateField(db_column='last_date'),
        ),
        migrations.AlterField(
            model_name='animalhealth',
            name='next_appointment',
            field=models.DateField(db_column='next_date'),
        ),
        migrations.AlterField(
            model_name='housingmanagement',
            name='last_cleaning',
            field=models.DateField(db_column='last_date'),
        ),
        migrations.AlterField(
            model_name='housingmanagement',
            name='next_cleaning',
            field=models.DateField(db_column='next_date'),
        ),
    ]
