# Generated by Django 5.0 on 2023-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_animalhealth_last_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalsAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('animal_type', models.CharField(max_length=200)),
                ('greed', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Adoption',
        ),
    ]
