# Generated by Django 5.0 on 2023-12-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_alter_animalsadoption_animals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimalsAdoption',
        ),
    ]
